server:
  port: 8081

spring:

  application:
    name: ds-server

  profiles:
    active: loc

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  task:
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 2m
      pool:
        core-size: 8
        max-size: 16
        keep-alive: 1m
        queue-capacity: 2048

  liquibase:
    change-log: classpath:/liquibase/changelog-master.xml
    database-change-log-lock-table: liquibase_changelog_lock
    database-change-log-table: liquibase_changelog


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeEnumsPackage: cn.fufeii.ds.common.enumerate.biz
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    # 二级缓存 关闭
    cache-enabled: false
  global-config:
    banner: false

# 按需生成日志文件
#logging:
#  file:
#    path: ./app_server_log

ds:
  server:
    enable-api-signature: true