spring:

  datasource:
    url: jdbc:mysql://mysql:3306/ds?characterEncoding=UTF-8&useSSL=false&useUnicode=true&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  redis:
    host: redis
    password: 123456

# 日志配置
logging:
  # 不要日志文件
  file:
    path: null
  level:
    cn.fufeii.ds.repository.dao: debug
    cn.fufeii.ds: debug

ds:
  server:
    enable-api-signature: false