spring:

  datasource:
    url: jdbc:mysql://localhost:3306/ds?characterEncoding=UTF-8&useSSL=false&useUnicode=true&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456

  redis:
    host: localhost
    password: 123456

#  liquibase:
#    enabled: true
