spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/distribution_sale?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: root