server:
  port: 8080

beetl:
  suffix: html
  templatesPath: templates

spring:
  application:
    name: ds-admin

  profiles:
    active: loc

  mvc:
    # 国际化固定为中国
    locale-resolver: fixed
    locale: zh_CN
    format:
      date-time: yyyy-MM-dd HH:mm:ss

  resources:
    # 静态资源地址
    static-locations: classpath:/static/

  jackson:
    time-zone: GMT+8
    date-format: ${spring.mvc.format.date-time}

# swagger相关配置
knife4j:
  enable: true

# mp
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeEnumsPackage: cn.fufeii.ds.common.enumerate.biz
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    cache-enabled: false
  global-config:
    banner: false

# 按需生成日志文件
#logging:
#  file:
#    path: ./app_admin_log

# admin配置
ds:
  admin:
    jwt-sign-key: ab012345678901234567890123456789
    jwt-sign-ttl: 12h
