server:
  port: 8080

spring:
  application:
    name: ds-admin
  profiles:
    active: local
  mvc:
    locale-resolver: fixed
    locale: zh_CN
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss