server:
  port: 8080

beetl:
  suffix: html
  templatesPath: templates

spring:
  application:
    name: ds-admin

  profiles:
    active: loc

  mvc:
    # 国际化固定为中国
    locale-resolver: fixed
    locale: zh_CN
    format:
      date-time: yyyy-MM-dd HH:mm:ss

  resources:
    # 静态资源地址
    static-locations: classpath:/static/

  jackson:
    time-zone: GMT+8
    date-format: ${spring.mvc.format.date-time}

  # FIXME 设置默认用户
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

# swagger相关配置
knife4j:
  enable: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeEnumsPackage: cn.fufeii.ds.common.enumerate.biz
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    # 二级缓存 关闭
    cache-enabled: false
  global-config:
    banner: false

logging:
  config: classpath:logback-spring.xml
  level:
    cn.fufeii.ds: debug
