spring:

  datasource:
    url: jdbc:mysql://localhost:3306/ds?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: 123456

  redis:
    host: localhost
    password: 123456